apiVersion: v1
kind: Service
metadata:
  name: cache-client
spec:
  type: NodePort
  selector:
    app: cache-client
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
